# Generated by Django 5.2.12 on 2026-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="description",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
