# Generated by Django 5.2.12 on 2026-03-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="codi_estacio",
        ),
    ]
