# Generated by Django 5.2.12 on 2026-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_user_codi_estacio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="codi_estacio",
            field=models.IntegerField(default=0),
        ),
    ]
