# Generated by Django 5.2.12 on 2026-03-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_codi_estacio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="codi_estacio",
        ),
    ]
