# Generated by Django 5.2.12 on 2026-03-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_merge_20260318_1627"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="codiEstacio",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
