# Generated by Django 5.2.12 on 2026-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_codiestacio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="codiEstacio",
            field=models.CharField(max_length=4),
        ),
    ]
