# Generated by Django 5.2.12 on 2026-03-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_user_codiestacio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="codiEstacio",
            new_name="stationCode",
        ),
    ]
